spring:
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    cache: false
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.mzr.blog.dao

comment.avatar: /images/avatar.png

#编码格式
server:
  tomcat:
    uri-encoding: UTF-8